name: Merge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-test-on-push:
    uses: ./.github/workflows/called.push.yml
  call-test-on-merge:
    needs: call-test-on-push
    uses: ./.github/workflows/called.merge.yml
