name: Merge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-on-merge:
    strategy:
      matrix:
        os: [macos-12, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and run on macos
        if: matrix.os == 'macos-12'
        run: |
          GOOS=darwin GOARCH=amd64 go build -o bin/go-dbdb-macos-amd64
          ./bin/go-dbdb-macos-amd64 mysql create --name=mysql57 --version 5.7.31 --port 53306
          ./bin/go-dbdb-macos-amd64 mysql start  --name=mysql57
          ./bin/go-dbdb-macos-amd64 mysql stop   --name=mysql57
          ./bin/go-dbdb-macos-amd64 mysql delete --name=mysql57
          ./bin/go-dbdb-macos-amd64 mysql create-start --name=mysql57 --version 5.7.31 --port 53306
      - name: Build and run on ubuntu
        if: matrix.os == 'ubuntu-22.04'
        run: |
          GOOS=linux GOARCH=amd64 go build -o bin/go-dbdb-linux-amd64
          ./bin/go-dbdb-linux-amd64 mysql create --name=mysql57 --version 5.7.31 --port 53306
          ./bin/go-dbdb-linux-amd64 mysql start  --name=mysql57
          ./bin/go-dbdb-linux-amd64 mysql stop   --name=mysql57
          ./bin/go-dbdb-linux-amd64 mysql delete --name=mysql57
          ./bin/go-dbdb-linux-amd64 mysql create-start --name=mysql57 --version 5.7.31 --port 53306
