name: Push

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - .*
  workflow_dispatch:

jobs:
  test-on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Run mysql test
        run: |
          uname -a
          go version
          go run main.go
          go run main.go mysql
          go run main.go mysql create --name=mysql57 --version 5.7.31 --port 53306
